# Site wide configuration

title: "Dr. Bang Ming Yong"
description: "This is a description of my awesome site."
logo: # 120x120 px default image used for Twitter summary card
teaser: # 400x250 px default teaser image used in image archive grid
locale: en
url: "https://bangtech.dev"
feed:
  path: atom.xml

# Jekyll configuration

sass:
  sass_dir: _sass
  style: compressed
permalink: /:categories/:title/
kramdown:
  toc_levels: 1..2
highlighter: rouge
plugins:
  - jekyll-sitemap
  - jekyll-gist
  - jekyll-feed

# footer links
footer-links:
  dribbble:
  email:
  facebook: yong.bang.ming
  flickr:
  github: yongbm
  instagram: yongbm89
  linkedin: bang-ming-yong-5111ab87
  pinterest:
  rss: # just type anything here for a working RSS icon
  twitter: ybming
  stackoverflow: # your stackoverflow profile, e.g. "users/50476/bart-kiers"
  youtube: dante10ybm # channel/<your_long_string> or user/<user-name>
  googleplus: # anything in your profile username that comes after plus.google.com/

#Google analytics
google_analytics: UA-228663747-1
google_analytics_4: G-FML4XS4XJ4

# Site owner
owner:
  name: Bang
  email:
  twitter:
  google:
    ad-client:
    ad-slot:
  bio:
  avatar: bio-photo.jpg # 160x160 px image for author byline
  disqus-shortname:

future: true
include:
  - .htaccess
exclude:
  - "*.less"
  - "*.sublime-project"
  - "*.sublime-workspace"
  - .asset-cache
  - .bundle
  - .jekyll-assets-cache
  - .sass-cache
  - CHANGELOG
  - Capfile
  - Gemfile
  - Gruntfile.js
  - LICENSE
  - README
  - Rakefile
  - config
  - gulpfile.js
  - lib
  - log
  - node_modules
  - package.json
  - spec
  - tmp
